from enum import Flag, auto

class Sector(Flag):
    CITY = auto()
    FIELD = auto()
    FOREST = auto()
    HILLS = auto()
    MOUNTAINS = auto()
    DEEPWATER = auto()
    DESERT = auto()
    ICE = auto()
    OCEAN = auto()
    VEHICLE = auto()
    SWAMP = auto()
    ROAD_RIGHT_DIAG = auto()
    ROAD_LEFT_DIAG = auto()
    ROAD_VERTICAL = auto()
    ROAD_HORIZONTAL = auto()
    ROAD_INTERSECTION = auto()
    RIVER_RIGHT_DIAG = auto()
    RIVER_LEFT_DIAG = auto()
    RIVER_VERTICAL = auto()
    RIVER_HORIZONTAL = auto()
    RIVER_INTERSECTION = auto()
